### PR TITLE
Waffle's Keymap

### PR DESCRIPTION
**Pull request by waffle87**
Can `keymapUrl` take two links?
eg. `keymapUrl: "link1 link2"`
If not, I don't have any other changes to make.
Thanks :^)

### CODE REVIEW

**Comment by precondition** [comment]
No, only one keymap URL is currently supported. I imagine your second link comes from that fact that you have a QMK and ZMK version right?

**Comment by waffle87** [comment]
Indeed. It's easy enough to find on my github anyway.

**Comment by precondition** [comment]
Can you leave your other link(s) here? You're not the only one who'd benefit from a list of URLs linking to different instances of the same keymap for different firmwares so I can look into turning the field into a `array[string]` later this week.

**Comment by waffle87** [comment]
Ah can do. 
[ZMK](https://github.com/waffle87/zmk-build) (I'll finish up readme in the next day or two)
[Kmonad](https://github.com/waffle87/dots/blob/xena/.config/apple_laptop.kbd) (lacks combos, but may be helpful for anyone setting it up)

**Pull request merged**
